<a href="https://colab.research.google.com/github/oerv13/Ibero/blob/main/FuncionesMedidas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Calculo de la Media
# La media es el promedio de un conjunto de valores. Se calcula sumando todos los valores y dividiéndolos por la cantidad total de elementos.
# Primero, sumamos todos los valores del conjunto de datos y dividimos por el número de valores para encontrar la media.



$$ \bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_{i} $$

In [ ]:
def media(lista):
  n = len(lista)
  sigma = sum(lista)
  return (1/n)*sigma

In [ ]:
lista_media = [1,2,3,4,5,6,7,8,9,10]
lista_media
media(lista_media)

5.5

In [ ]:
# Calculo de la Mediana
# La mediana es el valor que divide un conjunto de datos ordenados en dos partes iguales. Si el número de valores es impar, la mediana es el valor central; si es par,
# es el promedio de los dos valores centrales.
# Ordenamos el conjunto de datos y hallamos el valor central. Si el número de valores es par, promediamos los dos valores centrales.


$$ \bar{x} = \sum{1}+{n} \2 $$



In [ ]:
def mediana(lista_mediana):
    lista_mediana.sort()
    # Obtener longitud
    longitud = len(lista_mediana)
    # Mitad de la lista
    mitad = int(longitud / 2)
    # Si la longitud es par, promediar elementos centrales
    if longitud % 2 == 0:
        mediana = (lista_mediana[mitad - 1]+lista_mediana[mitad]) / 2
    else:
        # Si no es impar, es la del centro
        mediana = lista_mediana[mitad]
    return mediana

In [ ]:
lista_mediana = [10,40,20,50]
lista_mediana
mediana(lista_mediana)

30.0

In [ ]:
# Calculo de la Moda
# La moda es el valor que aparece con mayor frecuencia en un conjunto de datos. Un conjunto puede tener una o más modas.
# Contamos la frecuencia de cada valor y seleccionamos el valor que aparece con mayor frecuencia.

$$ \bar{x} = \frac{p}{c-p} $$

In [ ]:
def moda(lista_moda):
 frecuencias = {}
 for numero in lista_moda:
  if numero in frecuencias:
    frecuencias[numero] += 1
  else:
    frecuencias[numero] = 1

 moda = max(frecuencias, key=frecuencias.get)
 return moda


In [ ]:
lista_moda = [2,4,1,4,9,5,4]
lista_moda
moda(lista_moda)

4

In [ ]:
# Calculo de la Varianza
# La varianza mide la dispersión de los datos respecto a la media. Es la media de los cuadrados
# de las diferencias entre cada valor y la media del conjunto.
# Restamos la media de cada valor, elevamos al cuadrado cada diferencia, sumamos todas estas diferencias cuadradas y
# dividimos por el número total de valores.

$$ \bar{x} = \sum_{i=1}^{n} (x_{i}-x_)2 / {n -1}  $$

In [ ]:
def Varianza(lista_varianza):
 mean = (sum(lista_varianza) / len(lista_varianza))
 diff = [(v - mean) for v in lista_varianza]
 sqr_diff = [d**2 for d in diff]
 sum_sqr_diff = sum(sqr_diff)

 variance = sum_sqr_diff / (len(lista_varianza))
 #variance = variance**0.5
 return variance

In [ ]:
lista_varianza = [9,10,8,9,7]
lista_varianza
Varianza(lista_varianza)

1.0399999999999998

In [ ]:
# Calculo de la Desviacion Estandar
# La desviación estándar es la raíz cuadrada de la varianza y representa la dispersión promedio de los datos respecto a la media.
# Calculamos la raíz cuadrada de la varianza para obtener la desviación estándar.


$$ \bar{x} = (\sum_{i=1}^{n} (x_{i}-x_)2 / {n -1}) * 0.5  $$

In [ ]:
def DesEstandar(lista_DesEstandar):
 mean = (sum(lista_DesEstandar) / len(lista_DesEstandar))
 diff = [(v - mean) for v in lista_DesEstandar]
 sqr_diff = [d**2 for d in diff]
 sum_sqr_diff = sum(sqr_diff)

 variance = sum_sqr_diff / (len(lista_DesEstandar))
 variance = variance**0.5
 return variance

In [ ]:
lista_DesEstandar = [9,10,8,9,7]
lista_DesEstandar
DesEstandar(lista_DesEstandar)

1.0198039027185568

In [ ]:
#Coeficiente de Variacion
#El coeficiente de variación es una medida de dispersión relativa que se obtiene dividiendo la desviación estándar entre la media
# y se expresa como porcentaje.
#X: variable sobre la que se pretenden calcular la varianza
#Sx: Desviación típica de la variable X.
#| x̄ |: Es la media de la variable X en valor absoluto con x̄ ≠ 0
# Dividimos la desviación estándar por la media y multiplicamos por 100 para obtener el porcentaje de dispersión relativa.


$$ \bar{CV} = \frac {S} {|X<>0|} * 100 $$

In [ ]:
def CoeVar(lista_CV):
 #Desviacion Estandar
 mean = (sum(lista_DesEstandar) / len(lista_CV))
 diff = [(v - mean) for v in lista_CV]
 sqr_diff = [d**2 for d in diff]
 sum_sqr_diff = sum(sqr_diff)

 variance = sum_sqr_diff / (len(lista_CV))
 variance = variance**0.5

 #Media
 n = len(lista_CV)
 sigma = sum(lista_CV)
 media = (1/n)*sigma


 return (variance / media) * 100

In [ ]:
lista_CV = [9,10,8,9,7]
lista_CV
CoeVar(lista_CV)

11.858184915332057

In [ ]:
# Normalizacion Z
# La normalización Z, o estandarización, convierte cada valor en un conjunto de datos en una puntuación z.
# Esta puntuación indica cuántas desviaciones estándar está un valor por encima o por debajo de la media.
# X: Valor de Entrada
# Media
# Desviacion Estandar
# Para cada valor, restamos la media y dividimos por la desviación estándar, obteniendo una puntuación que permite
# comparar datos de diferentes escalas.


$$ {Z} = {X} - {media} / {Des Est} $$

In [ ]:
def NorZ(lista_NorZ,X):
 #Desviacion Estandar
 mean = (sum(lista_DesEstandar) / len(lista_NorZ))
 diff = [(v - mean) for v in lista_NorZ]
 sqr_diff = [d**2 for d in diff]
 sum_sqr_diff = sum(sqr_diff)

 variance = sum_sqr_diff / (len(lista_NorZ))
 variance = variance**0.5

 #Media
 n = len(lista_NorZ)
 sigma = sum(lista_NorZ)
 media = (1/n)*sigma


 return X - ((variance / media) * 100)

In [ ]:
lista_NorZ = [9,10,8,9,7]
lista_NorZ
NorZ(lista_NorZ,3)

-8.858184915332057

In [ ]:
# Referencias
# https://www.w3schools.com/python/ref_stat_median.asp
# https://geekflare.com/es/python-find-mean-median-and-mode/
# https://es.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/mean-median-basics/a/mean-median-and-mode-review#:~:text=Media%3A%20es%20el%20n%C3%BAmero%20%22promedio,entre%20el%20n%C3%BAmero%20de%20datos.
# https://quenube.com/como-encontrar-la-varianza-usando-python/
# https://medium.com/@rubenmndez/desviaci%C3%B3n-est%C3%A1ndar-y-varianza-3ba43e63f155
# https://fastercapital.com/es/tema/la-f%C3%B3rmula-para-el-coeficiente-de-correlaci%C3%B3n-de-pearson.html
# https://www.datacamp.com/es/tutorial/calculate-coefficient-variation-excel
# https://jorgeiblanco.medium.com/por-qu%C3%A9-la-normalizaci%C3%B3n-es-clave-e-importante-en-machine-learning-y-ciencia-de-datos-4595f15d5be0
# https://www.statology.org/z-score-normalization/


In [1]:
### Homework

# Numpy

import numpy as np
matriz = np.array([list(range(6)),list(range(5,11)),list(range(10,16)),list(range(15,21)),list(range(20,26))])
matriz

array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20],
       [20, 21, 22, 23, 24, 25]])

In [2]:
# Cree una matriz de 8x8 de valores enteros entre 0 y 20
# matriz = np.random.randint(0, 21, (8, 8))
valores = np.tile(np.arange(21), 4)[:64]
matriz = valores.reshape(8, 8)
print(matriz)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20  0  1  2]
 [ 3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18]
 [19 20  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20  0]]


In [3]:
# cree un objeto que sea la misma matriz pero con 4 columnas
print(matriz)
matriz_4_columnas = matriz.reshape(16, 4)
print(matriz_4_columnas)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20  0  1  2]
 [ 3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18]
 [19 20  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20  0]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]
 [19 20  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20  0]]


In [4]:
# acceda a la posición (6,4) de la matriz 1
print(matriz)
print(matriz[6,4])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20  0  1  2]
 [ 3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18]
 [19 20  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20  0]]
10


In [5]:
# acceda a la sub matriz de la matriz 1 que va de la fila 5 a la 8 y de la columna 3 a la 7
print(matriz)
submatriz = matriz[4:8, 2:7]
print(submatriz)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20  0  1  2]
 [ 3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18]
 [19 20  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20  0]]
[[13 14 15 16 17]
 [ 0  1  2  3  4]
 [ 8  9 10 11 12]
 [16 17 18 19 20]]
